#!/bin/sh
#
### BEGIN INIT INFO
# Provides:          etcd
# Required-Start:    $local_fs $remote_fs $network $syslog $named 
# Required-Stop:     $local_fs $remote_fs $network $syslog $named 
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# X-Interactive:     true
# Short-Description: Start/Stop A highly-available key value store for shared configuration and service discovery
### END INIT INFO

NAME=etcd
ETCDPATH="/opt/etcd"
ETCDBIN="$ETCDPATH/$NAME"
CONFFILE="/etc/avahi-ps-etcd.conf"
PIDFILE="/var/run/etcd.pid"
CURL="/usr/bin/curl"

BIND_IP="0.0.0.0"
MACHINE=$(uname -n)
OPTS=""
SERVER_ETCD_BASE="127.0.0.1:4001"
ETCD_PEER_PORT="7001"
ETCD_PORT="4001"
ETCD_LOG="/dev/null"

GTCONF="/etc/getinconf-client.conf"

test -f $GTCONF && . $GTCONF || exit 0

PUBLIC_DEVICE=${INTERNAL_DEV}
PUBLIC_IP=$(ip addr show dev $PUBLIC_DEVICE|grep "global $PUBLIC_DEVICE\$"|awk '{print $2}'|awk -F "/" {'print $1'})

test -f $CONFFILE && . $CONFFILE

[ -z "$ETCD_CONNECT" ] &&  PEERS="" || PEERS="-peers $ETCD_CONNECT"

remove_node() {
  # Remove etcd database
  rm -rf ${ETCDPATH}/machines/${MACHINE}.etcd
  # Get information
  my_node=($(${CURL} -s http://${PEERS}/v2/members|jq .members[]| jq -c '[.name,.id,.peerURLs[]]'|sed 's/^\[\(.*\)\]$/\1/'|sed 's/,/ /g'|grep \"${MACHINE}\"))
  [ ! -z $my_node ] && {
    # Need delete node.
    ${CURL} -s http://${PEERS}/v2/members/${my_node[1]} -X DELETE
  }  
}

add_node(){
  # Get node in cluster
  getnodes="$(echo $(curl -s http://${PEERS}/v2/members|jq .members[]| jq -c '[.name,.peerURLs[]]'|sed 's/^\["\(.*\)","\(.*\)"\]$/\1=\2/')|sed 's/ /,/g')"
  # Add node to cluster
  ${CURL} -s http://${PEERS}/v2/members -X POST -H "Content-Type: application/json" -d '{"peerURLs":["'${PUBLIC_IP}:${ETCD_PEER_PORT}'"]}'
  # Return 
  echo "${MACHINE}=${PUBLIC_IP},$getnodes"
}

start() {
	[ ! -f $ETCDBIN ] && { echo "etcd is not installed in $ETCDBIN."; exit 0; }
	mkdir -p $ETCDPATH/machines/

  remove_node

  export ETCD_INITIAL_CLUSTER="$(add_node)"
  export ETCD_INITIAL_CLUSTER_STATE=existing
  export ETCD_NAME="${MACHINE}"

  $ETCDBIN -name ${MACHINE} -initial-advertise-peer-urls http://${INTERNAL_IP}:${ETCD_PEER_PORT} -listen-peer-urls=http://${BIND_IP}:2380,http://${BIND_IP}:${ETCD_PEER_PORT} -listen-client-urls=http://${BIND_IP}:2379,http://${BIND_IP}:${ETCD_PORT} >> $ETCD_LOG 2>&1 &
#	$ETCDBIN -peer-bind-addr ${PUBLIC_IP}:${ETCD_PEER_PORT} -peer-addr ${PUBLIC_IP}:${ETCD_PEER_PORT} -bind-addr ${BIND_IP}:${ETCD_PORT} -addr ${BIND_IP}:${ETCD_PORT} $PEERS -data-dir $ETCDPATH/machines -name $MACHINE $OPTS >> $ETCD_LOG 2>&1 & 
	echo $! > $PIDFILE  
}
stop() {
  kill -9 $(cat $PIDFILE)
  rm $PIDFILE
}
restart() {
  stop
  sleep 0.5
  start
}

case "$1" in
  start)
    start
  ;;
  stop)
    stop
  ;;
  restart)
    restart
  ;;
  *)
    echo "Usage: /etc/init.d/$NAME {start|stop|restart}"
    exit 1
  ;;
esac

exit 0


